insert into empleado (id, nombre, apellido, sueldo, foto, fechaIngreso, fechaSalida) values (1, 'Rosario', 'Parrales', '200', 'http://dummyimage.com/243x100.png/dddddd/000000', '2-08-2010', '10-03-2014');
insert into empleado (id, nombre, apellido, sueldo, foto, fechaIngreso, fechaSalida) values (2, 'Coque', 'Calatrava', '300', 'http://dummyimage.com/215x100.png/cc0000/ffffff', '05-05-2011', '15-06-2018');

insert into productoporunidad (id, nombre, descripcion, likes, foto, precio, stock, discriminatoryValue) values (1, "Camiseta Mariscos Recio", "Camiseta de hombre talla M con el logo de la empresa para demostrar al mundo que comes el mejor marisco.", 500, 'http://dummyimage.com/243x100.png/dddddd/000000', 15, 300, "M");
insert into productoporunidad (id, nombre, descripcion, likes, foto, precio, stock, discriminatoryValue) values (2, "Taza Mariscos Recio", "Brillante y resistente taza de porcelana para disfrutar de un ColaCao con magdalenas como dios manda.", 234, 'http://dummyimage.com/243x100.png/dddddd/000000', 6, 60, "M");
insert into productoporunidad (id, nombre, descripcion, likes, foto, precio, stock, discriminatoryValue) values (3, "Llavero Mariscos Recio", "Llavero de acero inoxidable con algunas de las frases celebres del comercio.", 112, 'http://dummyimage.com/243x100.png/dddddd/000000', 3, 100, "M");
insert into productoporunidad (id, nombre, descripcion, likes, foto, precio, stock, discriminatoryValue) values (4, "Imán Nevera Mariscos Recio", "Imán decorativo con el logo de la empresa que le hará recordar nuestro delicioso género siempre que abra la nevera", 80, 'http://dummyimage.com/243x100.png/dddddd/000000', 2, 45, "M");
insert into productoporunidad (id, nombre, descripcion, likes, foto, precio, stock, discriminatoryValue) values (5, "Cena de Gala", "Si quiere una cena de gala, llévese una cigala. Este lote contiene 4kg de cigala que le permitirán alimentar a hasta 5 personas.", 37, 'http://dummyimage.com/243x100.png/dddddd/000000', 150, 3, "L");

insert into productoporpeso (id, nombre, descripcion, likes, foto, precio, stock, discriminatoryValue) values (1, "Lubina", "Si quiere una cena muy fina...¡Llévese una lubina!", 75, 'http://dummyimage.com/243x100.png/dddddd/000000', 22, 100, "P");
insert into productoporpeso (id, nombre, descripcion, likes, foto, precio, stock, discriminatoryValue) values (2, "Bogavante", "Si quiere una cena elegante... ¡Llévese un bogavante!", 120, 'http://dummyimage.com/243x100.png/dddddd/000000', 75, 130, "M");